name: Build and Release Electron App with Miners (Linux)

on:
  push:
    branches:
      - linux
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      XMRIG_URL: https://github.com/xmrig/xmrig/releases/download/v6.22.2/xmrig-6.22.2-jammy-x64.tar.gz 
      TREX_URL: https://github.com/trexminer/T-Rex/releases/download/0.26.8/t-rex-0.26.8-linux.tar.gz
      NODE_MODULES_URL: https://github.com/ChisdealHDAPP/nekosunevrapp-miner-modules/releases/download/1.0.0/node_modules.zip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Download and Extract Miners
        run: |
          mkdir -p miner/multi/xmrig
          mkdir -p miner/multi/trex
          curl -L "$XMRIG_URL" -o xmrig.tar.gz
          curl -L "$TREX_URL" -o trex.tar.gz
          tar -xzf xmrig.tar.gz -C miner/multi/xmrig
          tar -xzf trex.tar.gz -C miner/multi/trex

      - name: Clean up archives
        run: |
          rm -f xmrig.tar.gz
          rm -f trex.tar.gz

      - name: Flatten XMRig directory structure
        run: |
          mv miner/multi/xmrig/xmrig-6.22.2/* miner/multi/xmrig/
          rm -rf miner/multi/xmrig/xmrig-6.22.2

      - name: Verify Miner Layout
        run: |
          ls -la miner/multi/xmrig
          ls -la miner/multi/trex

      - name: Build Electron App
        run: npm run packager

      - name: Create ZIP
        run: |
          mkdir -p node_modules_temp

          echo "Downloading node_modules.zip..."
          curl -L "$NODE_MODULES_URL" -o node_modules.zip
          unzip node_modules.zip -d node_modules_temp

          for dir in dist/nekosunevrapp-miner-donations-linux-*; do
            arch_name=$(basename "$dir")
            echo "Packaging $arch_name..."

            mkdir -p release_temp
            cp -r "$dir"/* release_temp/

            rm -rf release_temp/resources/app/node_modules
            cp -r node_modules_temp/node_modules release_temp/resources/app/

            zip -r "${arch_name}.zip" release_temp

            rm -rf release_temp
          done

          rm -rf node_modules_temp node_modules.zip
          rm release.zip

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: linux-automated
          name: "Linux Auto Build ${{ github.run_number }}"
          body: "Zipped Linux builds for all architectures with miners and dependencies.\n\n## For make this work on Linux, Please install\n\n```sudo apt install libgconfig-2-4```"
          files: |
            *.zip
          draft: false
          prerelease: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
